/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.sql.ResultSet;

/**
 *
 * @author Ramlah Munir
 */
public class Admin_login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_login
     */
    public Admin_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sign_up = new javax.swing.JButton();
        forgot_password = new javax.swing.JButton();
        libraryManagementSystemLogin_label = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        Passwword_label = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        Password_field = new javax.swing.JPasswordField();
        message_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sign_up.setBackground(new java.awt.Color(255, 255, 204));
        sign_up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sign_up.setForeground(new java.awt.Color(0, 0, 102));
        sign_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/NEW USER.3.png"))); // NOI18N
        sign_up.setText("Sign up");
        sign_up.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 2, true));
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });
        getContentPane().add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 190, -1));

        forgot_password.setBackground(new java.awt.Color(255, 255, 204));
        forgot_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forgot_password.setForeground(new java.awt.Color(0, 0, 102));
        forgot_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/FORGOT PASSWORD RESIZED.png"))); // NOI18N
        forgot_password.setText("Forgot password");
        forgot_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 2, true));
        forgot_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 210, -1));

        libraryManagementSystemLogin_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        libraryManagementSystemLogin_label.setForeground(new java.awt.Color(0, 51, 102));
        libraryManagementSystemLogin_label.setText("Login to Library Management System");
        getContentPane().add(libraryManagementSystemLogin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 470, -1));

        login_btn.setBackground(new java.awt.Color(255, 255, 204));
        login_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_btn.setForeground(new java.awt.Color(0, 51, 102));
        login_btn.setText("Login");
        login_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 2, true));
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 80, 30));

        close_btn.setBackground(new java.awt.Color(255, 255, 204));
        close_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close_btn.setForeground(new java.awt.Color(0, 51, 102));
        close_btn.setText("Close");
        close_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 2, true));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 80, 30));

        username_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username_label.setForeground(new java.awt.Color(0, 0, 102));
        username_label.setText("Enter username: ");
        getContentPane().add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 200, -1));

        Passwword_label.setBackground(new java.awt.Color(204, 204, 255));
        Passwword_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Passwword_label.setForeground(new java.awt.Color(0, 0, 102));
        Passwword_label.setText("Enter your password : ");
        getContentPane().add(Passwword_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 220, -1));

        username_textfield.setBackground(new java.awt.Color(255, 255, 204));
        username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(username_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 240, -1));

        Password_field.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(Password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 240, -1));

        message_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        message_lbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(message_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 220, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/Untitled design.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SignUp().setVisible(true);
    }//GEN-LAST:event_sign_upActionPerformed

    private void forgot_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_passwordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Forgetpassword().setVisible(true);
    }//GEN-LAST:event_forgot_passwordActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        
        
        String userName=username_textfield.getText();
        String password=Password_field.getText();
        
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="select * from admin where username ='"+userName+"' and password = '"+password+"'";
            ResultSet result=obj.stmt.executeQuery(query);
            if(result.next()){
                setVisible(false);
            new admin_home().setVisible(true);
            } else {
                message_lbl.setText("Invalid username or password ");
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel Passwword_label;
    private javax.swing.JButton close_btn;
    private javax.swing.JButton forgot_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel libraryManagementSystemLogin_label;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel message_lbl;
    private javax.swing.JButton sign_up;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
