/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.sql.ResultSet;

/**
 *
 * @author Ramlah Munir
 */
public class admin_home extends javax.swing.JFrame {

    /**
     * Creates new form admin_home
     */
    public admin_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBooksBTN = new javax.swing.JButton();
        viewBooksBtn = new javax.swing.JButton();
        UpdateBooksBtn = new javax.swing.JButton();
        removeBooksBtn = new javax.swing.JButton();
        addStudentBTN = new javax.swing.JButton();
        vieStdntBtn = new javax.swing.JButton();
        UpdateStdntInfoBtnn = new javax.swing.JButton();
        removeStudenrBtn = new javax.swing.JButton();
        viewAvailableBooks_btn = new javax.swing.JButton();
        viewIssuedBooks = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("WELCOME TO LIBRARY MANAGEMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 710, 60));

        addBooksBTN.setBackground(new java.awt.Color(255, 204, 204));
        addBooksBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBooksBTN.setText("Add Books");
        addBooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBooksBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, 40));

        viewBooksBtn.setBackground(new java.awt.Color(255, 204, 204));
        viewBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewBooksBtn.setForeground(new java.awt.Color(102, 0, 51));
        viewBooksBtn.setText("View Books");
        viewBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 170, 40));

        UpdateBooksBtn.setBackground(new java.awt.Color(255, 204, 204));
        UpdateBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateBooksBtn.setForeground(new java.awt.Color(102, 0, 51));
        UpdateBooksBtn.setText("Update Books");
        UpdateBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBooksBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 170, 40));

        removeBooksBtn.setBackground(new java.awt.Color(255, 204, 204));
        removeBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeBooksBtn.setForeground(new java.awt.Color(102, 0, 51));
        removeBooksBtn.setText("Remove Books");
        removeBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBooksBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 170, 40));

        addStudentBTN.setBackground(new java.awt.Color(255, 204, 204));
        addStudentBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addStudentBTN.setForeground(new java.awt.Color(102, 0, 51));
        addStudentBTN.setText("Add Issuer");
        addStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addStudentBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 190, 40));

        vieStdntBtn.setBackground(new java.awt.Color(255, 204, 204));
        vieStdntBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vieStdntBtn.setForeground(new java.awt.Color(102, 0, 51));
        vieStdntBtn.setText("View Issuer");
        vieStdntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieStdntBtnActionPerformed(evt);
            }
        });
        getContentPane().add(vieStdntBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 190, 40));

        UpdateStdntInfoBtnn.setBackground(new java.awt.Color(255, 204, 204));
        UpdateStdntInfoBtnn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateStdntInfoBtnn.setForeground(new java.awt.Color(102, 0, 51));
        UpdateStdntInfoBtnn.setText("Update issuer_info");
        UpdateStdntInfoBtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStdntInfoBtnnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateStdntInfoBtnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 190, 40));

        removeStudenrBtn.setBackground(new java.awt.Color(255, 204, 204));
        removeStudenrBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeStudenrBtn.setForeground(new java.awt.Color(102, 0, 51));
        removeStudenrBtn.setText("Remove issuers");
        removeStudenrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudenrBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeStudenrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 190, 40));

        viewAvailableBooks_btn.setBackground(new java.awt.Color(255, 204, 204));
        viewAvailableBooks_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewAvailableBooks_btn.setForeground(new java.awt.Color(102, 0, 51));
        viewAvailableBooks_btn.setText("View Available books");
        viewAvailableBooks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailableBooks_btnActionPerformed(evt);
            }
        });
        getContentPane().add(viewAvailableBooks_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 190, 40));

        viewIssuedBooks.setBackground(new java.awt.Color(255, 204, 204));
        viewIssuedBooks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewIssuedBooks.setForeground(new java.awt.Color(102, 0, 51));
        viewIssuedBooks.setText("view Issued Books");
        viewIssuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIssuedBooksActionPerformed(evt);
            }
        });
        getContentPane().add(viewIssuedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 190, 40));

        jButton12.setBackground(new java.awt.Color(255, 204, 204));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(102, 0, 51));
        jButton12.setText("close");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 190, 40));

        jButton13.setBackground(new java.awt.Color(255, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(102, 0, 51));
        jButton13.setText("Sign out");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 190, 40));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("issue a book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 190, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 51));
        jButton2.setText("return book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 190, 40));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("search book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/hoem bg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateStdntInfoBtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStdntInfoBtnnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateIssuerInfo().setVisible(true);
    }//GEN-LAST:event_UpdateStdntInfoBtnnActionPerformed

    private void viewIssuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssuedBooksActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new viewissued_books().setVisible(true);
    }//GEN-LAST:event_viewIssuedBooksActionPerformed

    private void viewAvailableBooks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailableBooks_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AvailableBooks().setVisible(true);
    }//GEN-LAST:event_viewAvailableBooks_btnActionPerformed

    private void addBooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBooksBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Addbooks().setVisible(true);
        
    }//GEN-LAST:event_addBooksBTNActionPerformed

    private void addStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddIssuer().setVisible(true);
    }//GEN-LAST:event_addStudentBTNActionPerformed

    private void viewBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new view_books().setVisible(true);
    }//GEN-LAST:event_viewBooksBtnActionPerformed

    private void vieStdntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieStdntBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new viewissuer().setVisible(true);
    }//GEN-LAST:event_vieStdntBtnActionPerformed

    private void UpdateBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBooksBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new update_books().setVisible(true);
    }//GEN-LAST:event_UpdateBooksBtnActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Admin_login().setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void removeBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBooksBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Removebooks().setVisible(true);
    }//GEN-LAST:event_removeBooksBtnActionPerformed

    private void removeStudenrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudenrBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RemoveIssuer().setVisible(true);
    }//GEN-LAST:event_removeStudenrBtnActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new returnBook().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new searchBook().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBooksBtn;
    private javax.swing.JButton UpdateStdntInfoBtnn;
    private javax.swing.JButton addBooksBTN;
    private javax.swing.JButton addStudentBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton removeBooksBtn;
    private javax.swing.JButton removeStudenrBtn;
    private javax.swing.JButton vieStdntBtn;
    private javax.swing.JButton viewAvailableBooks_btn;
    private javax.swing.JButton viewBooksBtn;
    private javax.swing.JButton viewIssuedBooks;
    // End of variables declaration//GEN-END:variables
}
