package librarymanagementsystem;

import java.sql.ResultSet;

public class Forgetpassword extends javax.swing.JFrame {

    public Forgetpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        question_label = new javax.swing.JLabel();
        answer_textfield = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        message_label = new javax.swing.JLabel();
        next_Button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/FORGOT PASSWORD RESIZED.png"))); // NOI18N
        jLabel1.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 330, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Answer the given question.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 340, -1));

        question_label.setBackground(new java.awt.Color(255, 204, 204));
        question_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        question_label.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 370, 40));

        answer_textfield.setBackground(new java.awt.Color(255, 255, 204));
        answer_textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        answer_textfield.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(answer_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 340, 30));

        submitButton.setBackground(new java.awt.Color(255, 255, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 102));
        submitButton.setText("Submit");
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 2, true));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 80, 30));

        closeButton.setBackground(new java.awt.Color(255, 255, 204));
        closeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeButton.setForeground(new java.awt.Color(0, 0, 102));
        closeButton.setText("close");
        closeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 2, true));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Username/reg #:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        username_textfield.setBackground(new java.awt.Color(255, 255, 204));
        username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(username_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 180, 30));
        getContentPane().add(message_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 210, 40));

        next_Button.setBackground(new java.awt.Color(255, 204, 204));
        next_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next_Button.setForeground(new java.awt.Color(0, 0, 102));
        next_Button.setText("Next");
        next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(next_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));

        back_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(0, 0, 102));
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/hoem bg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        if (!isQuestionLoaded) {
            message_label.setText("firstly,enter username and click next");
            return;
        }
        String username = username_textfield.getText();
        String userAnswer = answer_textfield.getText().trim();  // Answer entered by user

        // Check if answer is empty
        if (userAnswer.isEmpty()) {
            message_label.setText("enter the answer");
            return;
        }
        try {
            ConnectionClass obj = new ConnectionClass();
            String query = "";
            query = "select security_question,security_answer from admin where username='" + username + "'";

            ResultSet result = obj.stmt.executeQuery(query);
            if (result.next()) {
                String correctAnswer = result.getString("security_answer").trim();
//        System.out.println("correct answer "+correctAnswer);
//        System.out.println("user answer "+userAnswer);
                if (userAnswer.equalsIgnoreCase(correctAnswer)) {
                    message_label.setText("answer verified.");
                    // Load the next screen (e.g., ResetPasswordFrame)

                    setPassword setFrame = new setPassword();
                    setFrame.setVisible(true);
                    this.setVisible(false);// Close current frame

                } else {
                    message_label.setText("Incorrect answer. Try again.");
                }
            } else {
                message_label.setText("User not found.");

            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("database error occured");
        }


    }//GEN-LAST:event_submitButtonActionPerformed

    private void username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textfieldActionPerformed
    //global variable
    String correctAnswer = "";
    boolean isQuestionLoaded = false;


    private void next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_ButtonActionPerformed
        // TODO add your handling code here:
        String username = username_textfield.getText();

        String userAnswer = answer_textfield.getText();
        if (username.isEmpty()) {
            message_label.setText("text field cannot be empty.");
            return;
        }

        try {

            ConnectionClass obj = new ConnectionClass();
            String query = "";

            query = "select security_question,security_answer from admin where username='" + username + "'";

            ResultSet result = obj.stmt.executeQuery(query);

            if (result.next()) {
                String question = result.getString("security_question");

                question_label.setText(question);
                isQuestionLoaded = true;
                message_label.setText(" ");
            } else {
                message_label.setText("username not found");
                isQuestionLoaded = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            message_label.setText("error connecting to database");
        }


    }//GEN-LAST:event_next_ButtonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_login().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer_textfield;
    private javax.swing.JButton back_button;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel message_label;
    private javax.swing.JButton next_Button;
    private javax.swing.JLabel question_label;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
