/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramlah Munir
 */
public class returnBook extends javax.swing.JFrame {

    /**
     * Creates new form returnBook
     */
    public returnBook() {
        initComponents();
        fetchBookId();
        fetch_issuedBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        returndateTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        returnbook = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        book_IDCOMBO = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Book_Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("return date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 140, 30));

        username_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username_txt.setForeground(new java.awt.Color(102, 0, 102));
        username_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 450, 30));

        returndateTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returndateTxt.setForeground(new java.awt.Color(102, 0, 102));
        returndateTxt.setText("yyyy-mm-dd");
        returndateTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        returndateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndateTxtActionPerformed(evt);
            }
        });
        getContentPane().add(returndateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 450, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("return a book");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 170, 40));

        returnbook.setText("return");
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        getContentPane().add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 100, 40));

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 100, 40));
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 480, 40));

        book_IDCOMBO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        book_IDCOMBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_IDCOMBOActionPerformed(evt);
            }
        });
        getContentPane().add(book_IDCOMBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 450, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "book_id", "username", "issue_date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 800, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/hoem bg.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returndateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndateTxtActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
        // TODO add your handling code here:
        String book_Id= (String) book_IDCOMBO.getSelectedItem();
        String username=username_txt.getText();
        String returnDate=returndateTxt.getText();
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="insert into returnbooks (Book_id,username,return_Date) values('"+book_Id+"','"+username+"','"+returnDate+"')";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("Book returned successfully.");
                try {
                    String chanfeAvailability="update books set available = 1  where book_id='"+book_Id+"'";
                    int rowschanged1=obj.stmt.executeUpdate(chanfeAvailability);
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
                try{
                String removeFromIssued="delete from issuedbooks where Book_id = '"+book_Id+"'";
                int rowschanged2=obj.stmt.executeUpdate(removeFromIssued);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            } else {
                message.setText("Book  did not returned successfully.");
            }
        }catch (Exception e) {
            message.setText("An error occurred while returning the book.");
            e.printStackTrace();
        }
        //

    }//GEN-LAST:event_returnbookActionPerformed

    private void fetch_issuedBooks(){
        DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
       try {
            ConnectionClass obj=new ConnectionClass();
            String query="select * from issuedbooks";
            ResultSet result=obj.stmt.executeQuery(query);
            while(result.next()){
                String id=result.getString("id");
                String bookId=result.getString("Book_id");
                String username=result.getString("username");
                String issue_date=result.getString("issue_date");
                table.addRow(new Object[] {id,bookId,username,issue_date});
           }
            }
        catch (Exception e) {
            e.printStackTrace();
        }
    }         
    private void fetchBookId(){
        try {
            ConnectionClass obj = new ConnectionClass();
            String query = "select Book_id from issuedbooks ";
            ResultSet result=obj.stmt.executeQuery(query);
            book_IDCOMBO.removeAllItems();
            while (result.next()){
                book_IDCOMBO.addItem(result.getString("Book_id"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void book_IDCOMBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_IDCOMBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_IDCOMBOActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> book_IDCOMBO;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel message;
    private javax.swing.JButton returnbook;
    private javax.swing.JTextField returndateTxt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
