/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;


/**
 *
 * @author T490
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUp = new javax.swing.JButton();
        confirmpaswords = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        email = new javax.swing.JLabel();
        answertxt = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        usernametxtfield = new javax.swing.JTextField();
        fullName = new javax.swing.JLabel();
        full_name_txtfield = new javax.swing.JTextField();
        securityQuestion = new javax.swing.JLabel();
        answer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        securityquestion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        email_txtfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUp.setBackground(new java.awt.Color(255, 255, 204));
        signUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUp.setForeground(new java.awt.Color(0, 0, 102));
        signUp.setText("Signup");
        signUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 2, true));
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        getContentPane().add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 90, -1));

        confirmpaswords.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(confirmpaswords, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 320, -1));

        confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmPassword.setForeground(new java.awt.Color(0, 0, 102));
        confirmPassword.setText("Confirm Password");
        getContentPane().add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 130, 20));

        passwordtxt.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 320, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 102));
        email.setText("Email Address");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 20));

        answertxt.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(answertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 300, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 102));
        username.setText("UserName / reg# ");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 130, 20));

        usernametxtfield.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(usernametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 320, -1));

        fullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullName.setForeground(new java.awt.Color(0, 0, 102));
        fullName.setText("Enter Full name");
        getContentPane().add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 120, 20));

        full_name_txtfield.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(full_name_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 320, -1));

        securityQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        securityQuestion.setForeground(new java.awt.Color(0, 0, 102));
        securityQuestion.setText("Enter security question in case you forgot password : ");
        getContentPane().add(securityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 460, 20));

        answer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answer.setForeground(new java.awt.Color(0, 0, 102));
        answer.setText("Answer above question");
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 170, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 130, -1));

        securityquestion.setBackground(new java.awt.Color(255, 255, 204));
        securityquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityquestionActionPerformed(evt);
            }
        });
        getContentPane().add(securityquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 470, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 80, -1));
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 210, 20));

        email_txtfield.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(email_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 320, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/Untitled (121 x 50 px) (450 x 50 px).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 480, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/Untitled design.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void securityquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityquestionActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
        String full_name=full_name_txtfield.getText();
        String email=answertxt.getText();
        String username=usernametxtfield.getText();
        String password=passwordtxt.getText();
        String confirmPswrd=confirmpaswords.getText();
        String security_question=securityquestion.getText();
        String security_answer=answertxt.getText();
        if(password.equals(confirmPswrd)){
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="";
                query="insert into admin(username,full_name,email,password,security_question,security_answer)values('"+username+"','"+full_name+"','"+email+"','"+password+"','"+security_question+"','"+security_answer+"')";
           
            
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("signed up successfully.");
            } else {
                message.setText("error occured during signing up");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while adding the issuer.");
            e.printStackTrace();
        }
        }
        else{
            message.setText("password and confirm password must be same");
        }
    }//GEN-LAST:event_signUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Admin_login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer;
    private javax.swing.JTextField answertxt;
    private javax.swing.JLabel confirmPassword;
    private javax.swing.JPasswordField confirmpaswords;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_txtfield;
    private javax.swing.JLabel fullName;
    private javax.swing.JTextField full_name_txtfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel securityQuestion;
    private javax.swing.JTextField securityquestion;
    private javax.swing.JButton signUp;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables
}
