/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import com.mysql.cj.callback.UsernameCallback;
import librarymanagementsystem.admin_home;

/**
 *
 * @author T490
 */
public class UpdateIssuerInfo extends javax.swing.JFrame {

    /**
     * Creates new form UpdateIssuerInfo
     */
    public UpdateIssuerInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IssuerSecurityQuestion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IssuerAnswer = new javax.swing.JTextField();
        IssuerPassword = new javax.swing.JPasswordField();
        issuerUserName = new javax.swing.JTextField();
        issuerEmail = new javax.swing.JTextField();
        IssuerFullName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updatefullname_btn = new javax.swing.JButton();
        updateemail_btn = new javax.swing.JButton();
        updatepassword_btn = new javax.swing.JButton();
        updatesecurityq_btn = new javax.swing.JButton();
        updateanswer_btn = new javax.swing.JButton();
        message = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Update Issuer_information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Email Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 150, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 150, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 150, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Security Question");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 170, 30));

        IssuerSecurityQuestion.setBackground(new java.awt.Color(255, 255, 204));
        IssuerSecurityQuestion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IssuerSecurityQuestion.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(IssuerSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 450, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 80, 30));

        IssuerAnswer.setBackground(new java.awt.Color(255, 255, 204));
        IssuerAnswer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IssuerAnswer.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(IssuerAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 450, -1));

        IssuerPassword.setBackground(new java.awt.Color(255, 255, 204));
        IssuerPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IssuerPassword.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(IssuerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 250, -1));

        issuerUserName.setBackground(new java.awt.Color(255, 255, 204));
        issuerUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issuerUserName.setForeground(new java.awt.Color(0, 0, 102));
        issuerUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuerUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(issuerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 250, -1));

        issuerEmail.setBackground(new java.awt.Color(255, 255, 204));
        issuerEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issuerEmail.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(issuerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 250, -1));

        IssuerFullName.setBackground(new java.awt.Color(255, 255, 204));
        IssuerFullName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IssuerFullName.setForeground(new java.awt.Color(0, 0, 102));
        IssuerFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuerFullNameActionPerformed(evt);
            }
        });
        getContentPane().add(IssuerFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 250, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 130, 30));

        updatefullname_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatefullname_btn.setForeground(new java.awt.Color(0, 0, 102));
        updatefullname_btn.setText("update full name");
        updatefullname_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefullname_btnActionPerformed(evt);
            }
        });
        getContentPane().add(updatefullname_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 210, 30));

        updateemail_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateemail_btn.setForeground(new java.awt.Color(0, 0, 102));
        updateemail_btn.setText("update email address");
        updateemail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateemail_btnActionPerformed(evt);
            }
        });
        getContentPane().add(updateemail_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 210, 30));

        updatepassword_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatepassword_btn.setForeground(new java.awt.Color(0, 0, 102));
        updatepassword_btn.setText("update password");
        updatepassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassword_btnActionPerformed(evt);
            }
        });
        getContentPane().add(updatepassword_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 210, 30));

        updatesecurityq_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatesecurityq_btn.setForeground(new java.awt.Color(0, 0, 102));
        updatesecurityq_btn.setText("update security question");
        updatesecurityq_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesecurityq_btnActionPerformed(evt);
            }
        });
        getContentPane().add(updatesecurityq_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 210, 30));

        updateanswer_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateanswer_btn.setForeground(new java.awt.Color(0, 0, 102));
        updateanswer_btn.setText("update answer");
        updateanswer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateanswer_btnActionPerformed(evt);
            }
        });
        getContentPane().add(updateanswer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 210, 30));

        message.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 550, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/hoem bg.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuerUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuerUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuerUserNameActionPerformed

    private void IssuerFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuerFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuerFullNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updatefullname_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefullname_btnActionPerformed
        // TODO add your handling code here:
        String username=issuerUserName.getText();
        String full_name=IssuerFullName.getText();
        
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update issuer set full_name='"+full_name+"'  where username='"+username+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("issuer full name updated successfully.");
            } else {
                message.setText("issuer full name did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating full name.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatefullname_btnActionPerformed

    private void updateemail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateemail_btnActionPerformed
        // TODO add your handling code here:
        String username=issuerUserName.getText();
        String email=issuerEmail.getText();
        
        try{
            ConnectionClass obj=new ConnectionClass();
            String query="update issuer set email='"+email+"'  where username='"+username+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("issuer email updated successfully.");
            } else {
                message.setText("issuer email did not updated successfully.");
            }
        }
        catch(Exception e){
            message.setText("an error occured while updating email.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateemail_btnActionPerformed

    private void updatepassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassword_btnActionPerformed
        // TODO add your handling code here:
        String username=issuerUserName.getText();
        String password=IssuerPassword.getText();
        
        try{
            ConnectionClass obj=new ConnectionClass();
            String query="update issuer set password='"+password+"'  where username='"+username+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("issuer password updated successfully.");
            } else {
                message.setText("issuer password did not updated successfully.");
            }
        }
        catch(Exception e){
            message.setText("an error occured while updating password.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatepassword_btnActionPerformed

    private void updatesecurityq_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesecurityq_btnActionPerformed
        // TODO add your handling code here:
        String username=issuerUserName.getText();
        String security_question=IssuerSecurityQuestion.getText();
        
        try{
            ConnectionClass obj=new ConnectionClass();
            String query="update issuer set security_question='"+security_question+"'  where username='"+username+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("issuer security question updated successfully.");
            } else {
                message.setText("issuer security question did not updated successfully.");
            }
        }
        catch(Exception e){
            message.setText("an error occured while updating security question.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatesecurityq_btnActionPerformed

    private void updateanswer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateanswer_btnActionPerformed
        // TODO add your handling code here:
        String username=issuerUserName.getText();
        String answer=IssuerAnswer.getText();
        
        try{
            ConnectionClass obj=new ConnectionClass();
            String query="update issuer set security_answer='"+answer+"'  where username='"+username+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("issuer answer updated successfully.");
            } else {
                message.setText("issuer answer did not updated successfully.");
            }
        }
        catch(Exception e){
            message.setText("an error occured while updating answer.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateanswer_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateIssuerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateIssuerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateIssuerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateIssuerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateIssuerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IssuerAnswer;
    private javax.swing.JTextField IssuerFullName;
    private javax.swing.JPasswordField IssuerPassword;
    private javax.swing.JTextField IssuerSecurityQuestion;
    private javax.swing.JTextField issuerEmail;
    private javax.swing.JTextField issuerUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField message;
    private javax.swing.JButton updateanswer_btn;
    private javax.swing.JButton updateemail_btn;
    private javax.swing.JButton updatefullname_btn;
    private javax.swing.JButton updatepassword_btn;
    private javax.swing.JButton updatesecurityq_btn;
    // End of variables declaration//GEN-END:variables
}
