/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

/**
 *
 * @author Fame
 */
public class update_books extends javax.swing.JFrame {

    /**
     * Creates new form update_books
     */
    public update_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        title_txt = new javax.swing.JTextField();
        author_txt = new javax.swing.JTextField();
        publisher_txt = new javax.swing.JTextField();
        edition_txt = new javax.swing.JTextField();
        category_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        location_txt = new javax.swing.JTextField();
        message = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        updateTitle = new javax.swing.JButton();
        updateAuthor = new javax.swing.JButton();
        updatePublisher = new javax.swing.JButton();
        updateEdition = new javax.swing.JButton();
        updateCtegory = new javax.swing.JButton();
        update_shelf_location = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Book_ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("Author");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 337, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("update Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 51));
        jLabel9.setText("Edition");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Publisher");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Book_title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Shelf_Location");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 130, 30));
        getContentPane().add(title_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 300, 30));

        author_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author_txtActionPerformed(evt);
            }
        });
        getContentPane().add(author_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 300, 30));

        publisher_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisher_txtActionPerformed(evt);
            }
        });
        getContentPane().add(publisher_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 300, 30));
        getContentPane().add(edition_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 300, 30));
        getContentPane().add(category_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 300, 30));
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 220, 30));
        getContentPane().add(location_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 300, 30));

        message.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 640, 30));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 51));
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, 110, -1));

        updateTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTitle.setForeground(new java.awt.Color(102, 0, 102));
        updateTitle.setText("update title");
        updateTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTitleActionPerformed(evt);
            }
        });
        getContentPane().add(updateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 240, 30));

        updateAuthor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateAuthor.setForeground(new java.awt.Color(102, 0, 102));
        updateAuthor.setText("update author");
        updateAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(updateAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 240, 30));

        updatePublisher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePublisher.setForeground(new java.awt.Color(102, 0, 102));
        updatePublisher.setText("update publisher");
        updatePublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePublisherActionPerformed(evt);
            }
        });
        getContentPane().add(updatePublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 240, 30));

        updateEdition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateEdition.setForeground(new java.awt.Color(102, 0, 102));
        updateEdition.setText("update edition");
        updateEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEditionActionPerformed(evt);
            }
        });
        getContentPane().add(updateEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 240, 30));

        updateCtegory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateCtegory.setForeground(new java.awt.Color(102, 0, 102));
        updateCtegory.setText("update category");
        updateCtegory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCtegoryActionPerformed(evt);
            }
        });
        getContentPane().add(updateCtegory, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 240, 30));

        update_shelf_location.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_shelf_location.setForeground(new java.awt.Color(102, 0, 102));
        update_shelf_location.setText("update shelf location");
        update_shelf_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_shelf_locationActionPerformed(evt);
            }
        });
        getContentPane().add(update_shelf_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 240, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/hoem bg.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_author_txtActionPerformed

    private void publisher_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisher_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisher_txtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new admin_home().setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTitleActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String book_title=title_txt.getText();
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set Title='"+book_title+"'  where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book title updated successfully.");
            } else {
                message.setText("book title did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating book title.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_updateTitleActionPerformed

    private void updateAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAuthorActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String author=author_txt.getText();

        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set Author='"+author+"' where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book author updated successfully.");
            } else {
                message.setText("book author did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating the book author.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_updateAuthorActionPerformed

    private void updatePublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePublisherActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String publisher=publisher_txt.getText();
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set publisher='"+publisher+"'  where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book publisher updated successfully.");
            } else {
                message.setText("book publisher did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating the book publisher.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_updatePublisherActionPerformed

    private void updateEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEditionActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String edition=edition_txt.getText();

        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set Edition='"+edition+"'  where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book edition updated successfully.");
            } else {
                message.setText("book edition did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating the book edition.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_updateEditionActionPerformed

    private void updateCtegoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCtegoryActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String category=category_txt.getText();
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set category='"+category+"'  where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book category updated successfully.");
            } else {
                message.setText("book category did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating the book category.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_updateCtegoryActionPerformed

    private void update_shelf_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_shelf_locationActionPerformed
        // TODO add your handling code here:
        String book_Id=id_txt.getText();
        String shelf_location=location_txt.getText();
        try {
            ConnectionClass obj=new ConnectionClass();
            String query="update books set shelf_no='"+shelf_location+"'  where book_id='"+book_Id+"'";
            int rowschanged=obj.stmt.executeUpdate(query);
            if(rowschanged>0){
                message.setText("book location updated successfully.");
            } else {
                message.setText("book location did not updated successfully.");
            }
        }
        catch (Exception e) {
            message.setText("An error occurred while updating the location of book.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_update_shelf_locationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author_txt;
    private javax.swing.JTextField category_txt;
    private javax.swing.JTextField edition_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField location_txt;
    private javax.swing.JTextField message;
    private javax.swing.JTextField publisher_txt;
    private javax.swing.JTextField title_txt;
    private javax.swing.JButton updateAuthor;
    private javax.swing.JButton updateCtegory;
    private javax.swing.JButton updateEdition;
    private javax.swing.JButton updatePublisher;
    private javax.swing.JButton updateTitle;
    private javax.swing.JButton update_shelf_location;
    // End of variables declaration//GEN-END:variables
}
